// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAArmFPqMrK9_wfjyWT7k1lt9sB95WXVUg',
    appId: '1:987753303073:web:420e72787feae70225e760',
    messagingSenderId: '987753303073',
    projectId: 'kick-reals-4c454',
    authDomain: 'kick-reals-4c454.firebaseapp.com',
    storageBucket: 'kick-reals-4c454.appspot.com',
    measurementId: 'G-H66F4K7ZZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkRVaZOWMbqBcXzbZ5W73PrjG9dwupNE',
    appId: '1:987753303073:android:85b970c625b0470f25e760',
    messagingSenderId: '987753303073',
    projectId: 'kick-reals-4c454',
    storageBucket: 'kick-reals-4c454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJQOx6Ij3NVVUza7xWfFLTIy7CDUBhos',
    appId: '1:987753303073:ios:c6928488fbecadaa25e760',
    messagingSenderId: '987753303073',
    projectId: 'kick-reals-4c454',
    storageBucket: 'kick-reals-4c454.appspot.com',
    iosBundleId: 'com.example.kickReels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJQOx6Ij3NVVUza7xWfFLTIy7CDUBhos',
    appId: '1:987753303073:ios:c6928488fbecadaa25e760',
    messagingSenderId: '987753303073',
    projectId: 'kick-reals-4c454',
    storageBucket: 'kick-reals-4c454.appspot.com',
    iosBundleId: 'com.example.kickReels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAArmFPqMrK9_wfjyWT7k1lt9sB95WXVUg',
    appId: '1:987753303073:web:c067203c53fecc3625e760',
    messagingSenderId: '987753303073',
    projectId: 'kick-reals-4c454',
    authDomain: 'kick-reals-4c454.firebaseapp.com',
    storageBucket: 'kick-reals-4c454.appspot.com',
    measurementId: 'G-BYWPLPH42T',
  );
}
